### ISSUE TITLE
Review and update documentation before the milestone release.

### ISSUE THREAD

**Issue by pellico** [Infineon/svd2pac#20]
**Is your feature request related to a problem? Please describe.**
Documentation of tool is not fully clear the following topic needs to addressed:

- [x] Add doc example for read and write register
- [x] Clarify the objective of tool 
- [x] Review example in documentation except tracing feature
- [x] Review examples in documentation of tracing feature
- [x] Review documentation of generated PAC
